import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/navigation";
import getLoggedUserID from "./_actions/getLoggedUserID";
import { auth } from "@/auth";
import { getUserByID } from "./_services/userServices/getUserByID";
import { Toaster } from "@/components/ui/toaster";
import { SocketProvider } from "./context/SocketContext";
import { UserProvider } from "./context/UserContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <SocketProvider>
          <body
            className={inter.className + " dark min-h-screen flex flex-col"}
          >
            <Navigation />
            {children}
            <Toaster />
          </body>
        </SocketProvider>
      </UserProvider>
    </html>
  );
}
