import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/navigation";
import getLoggedUserID from "./_actions/getLoggedUserID";
import { auth } from "@/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getLoggedUserID();
  const OAuthSession = await auth();
  return (
    <html lang="en">
      <body className={inter.className + " dark "}>
        {(user || OAuthSession) && <Navigation />}
        {children}
      </body>
    </html>
  );
}
